# Generated by Django 2.2 on 2020-10-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201003_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='titletranslate',
            field=models.TextField(default='illum ipsum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beginners',
            name='titletranslate',
            field=models.TextField(default='illum ipsom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intermediate',
            name='titletranslate',
            field=models.TextField(default='ilum ipsom'),
            preserve_default=False,
        ),
    ]
